name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: ls -l 
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: 159.89.89.13
        username: root
        key: ${{ secrets.SSH_PRIVATE }}
        port: 22
        script: whoami
    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      env:
        HOST: 159.89.89.13
        USERNAME: root
        PORT: 22
        KEY: ${{ secrets.SSH_PRIVATE }}
      with:
        source: "./index.html"
        target: "/var/www/html"
